- name: Testing Environment
  hosts: all
  vars:
    jenkins_home: /var/lib/jenkins/
    num_executors: 4
  roles:
    - browsers
    - djangodata
    - git
    - memcached
    - mysql
    - postgres
    - python